language: php

cache:
  directories:
  - bin
  - vendor

matrix:
  fast_finish: true

php:
- 7.1
- 7.0
- 5.6

before_install:
- composer self-update

install:
- composer install --no-interaction --prefer-dist --no-scripts

script:
- composer validate
- vendor/bin/phing ci

after_success:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
