language: php

cache:
    directories:
    - bin
    - vendor

php:
- 7.1
- 7.0
- 5.6

before_install:
- phpenv config-rm xdebug.ini
- composer self-update

install:
- composer install --no-interaction --prefer-dist --no-scripts

script:
- composer validate
- vendor/bin/phing ci
